Create testing for abc_atlas_cache objects
AllenInstitute/abc_atlas_access pull request #43
Opened 2024-03-06 01:54 UTC by morriscb

Add testing for S3CloudCache object.
Add testing for LocalCache object.
Add testing for AbcProjectCache from s3 and local.

2024-03-06 01:56 UTC, morriscb commented
Hey @danielsf I think I have a fare port of the unittesting from the SDK caches to here. Tried to clean things up a bit before sending it your way though my expectation of this review is that it will be pretty back and forth as you remember the previous testing and I try to implement what's missing, simplify/remove duplicate code.

2024-07-15 18:56 UTC, danielsf requested changes
Mostly some documentation requests.

There are a few cases where I ask that you clean up the SDK code you inherited (using `pytest.warns(...., match='...')` where I think it is possible. If I am wrong that this isn't possible (I know warnings are a pain), feel free to ignore.

2024-07-15 18:56 UTC, danielsf commented on tests/abc_atlas_cache/utils.py
> +def create_bucket(region_name: str,
I'm being a little paranoid here, but can we make this a member of BaseCacheTestCase so no one accidentally calls this outside of a `@mock_aws` invocation.

Or else wrap this function in `@mock_aws` to be doubly-sure. When I first saw this function I did a double-take before realizing that it is only ever invoked in classes wrapped with `@mock_aws`

2024-07-15 18:56 UTC, danielsf commented on tests/abc_atlas_cache/test_cache.py
> +        assert 'but is not a file' in context.value.args[0]
I suspect this was copy-and-pasted from SDK code written when *somebody* (cough, cough) wasn't totally comfortable with `pytest.raises`. Do you mind fixing this to use `pytest.raises(...., match='but is not a file')`

2024-07-15 18:56 UTC, danielsf commented on tests/abc_atlas_cache/test_cache.py
> +        Test that S3CloudCache.download_data() correctly downloads files from
This test no longer (or never did) downloads the data. It just checks that the `CacheFileAttributes` is correctly formulated (specifically, it asserts that the files it inquires about do not exist). Can you update the docstring?

2024-07-15 18:56 UTC, danielsf commented on tests/abc_atlas_cache/test_cache.py
> +                assert 'is not the most up to date' in msg
Can this also be done with `match=...` in the `pytest.warns()` context?

2024-07-15 18:56 UTC, danielsf commented on tests/abc_atlas_cache/test_cache.py
> +        # not OutdatedManifestWarnings
this comment is no longer accurate (I think *any* warning will cause the test to fail).

2024-07-15 18:56 UTC, danielsf commented on tests/abc_atlas_cache/test_cache.py
> +        Test that S3CloudCache.download_data() correctly files in the directory
Check the grammar on this docstring. I think it is supposed to be

"Test that S3CloudCache.download_data() correctly downloads files from S3"

2024-07-15 18:56 UTC, danielsf commented on tests/abc_atlas_cache/test_cache.py
> +        # test data_path
Can you flesh out the comment (or docstring) to explain that, the difference between the `download_data` calls that fail and those that succeed is `skip_hash_check`?

2024-07-15 21:58 UTC, danielsf approved these changes
looks good

2024-07-17 17:05 UTC, merged